[project]
name = "hepo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium[box2d]>=1.2.2",
    "numpy>=2.3.5",
    "stable-baselines3[extra]>=2.7.0",
    "torch>=2.9.1",
]
